import {test,expect} from '@playwright/test';
async function start(page){
 await page.goto('/wiki-preview.html');
 await page.addScriptTag({url:'/js/project-journal.js'});
 await page.addStyleTag({url:'/css/project-journal.css'});
 await page.evaluate(()=>{
  const entry=(id,kind,content,ticket='DEMO-1')=>({id,kind,content,ticket,title:id,at:'2026-10-03T20:00:00Z',actor:kind==='note'?'André':'@Reviewer',thread_id:'thread-one',agent:'reviewer'});
  window.journalData={project:{key:'DEMO',name:'Backup review',purpose:'Review the existing system and preserve recovery evidence.'},path:'Development/journal/2026-10-03.md',documents:[{path:'Development/journal/2026-10-03.md'}],opening:'## Previous work\n\nInventory completed. Restore validation remains open.\n\n[Previous Journal](../../Development/journal/2026-10-02.md)\n\n[Design reference](https://example.com/design)',entries:[entry('one','decision','### Preserve existing archives\n\nAgreed by André. Retention changes need a separate review.'),entry('two','finding','### Missing validation\n\nThe script does not check the result.\n\n```js\n'+Array.from({length:18},(_,i)=>`check(${i});`).join('\n')+'\n```'),entry('three','note','### Your question\n\nCan we verify recovery before changing the schedule?','DEMO-2')],runs:[],observed_at:'2026-10-03T20:02:00Z',warning:''};
  window.journalCalls=[];window.__TAURI__={core:{invoke:async(name,args)=>{
   window.journalCalls.push({name,args});
   if(name==='project_journal_read'){if(args.project==='OTHER')return {...window.journalData,project:{key:'OTHER',name:'Other'},entries:[],opening:'Other project history',documents:[]};return structuredClone(window.journalData);}
   if(name==='project_journal_add'){if(window.failSave)throw Error('Ticket is outside this project');window.journalData.entries.push(entry('saved','note','### Your note\n\n'+args.request.content,args.request.ticket));return {ok:true};}
   if(name==='project_wiki_source')return {title:'Run receipt',text:'Recorded state'};
  }}};
  window.xnautOpenAgentSpace=(...args)=>{window.openedConversation=args;};
  document.body.innerHTML='<div id="journal" style="height:900px;width:660px"></div>';
  window.journalInstance=window.xnautJournal.mount(document.querySelector('#journal'),'DEMO',path=>{window.openedWiki=path;});
 });
 await expect(page.locator('[data-title]')).toHaveText('Backup review · Live Journal');
}
test('working document shows history, highlighted decisions, human notes and expandable code',async({page})=>{await start(page);await expect(page.locator('[data-opening]')).toContainText('Restore validation remains open');await expect(page.locator('.pj-decision')).toContainText('Agreed by André');await expect(page.locator('.pj-note')).toContainText('André');await expect(page.locator('.pj-body details')).not.toHaveAttribute('open');await page.locator('.pj-body summary').click();await expect(page.locator('pre')).toContainText('check(17)');await page.locator('[data-wiki]').click();expect(await page.evaluate(()=>window.openedWiki)).toBe('Development/journal/2026-10-03.md');});
test('live refresh retains expanded code, reading position and note draft',async({page})=>{await page.clock.install();await start(page);await page.locator('.pj-body summary').click();await page.getByText('Add your note or question',{exact:true}).click();await page.locator('[data-note]').fill('Keep my draft');await page.locator('.pj-scroll').evaluate(e=>{e.scrollTop=170;});const scroll=await page.locator('.pj-scroll').evaluate(e=>e.scrollTop);await page.evaluate(()=>window.journalData.entries.push({...window.journalData.entries[0],id:'four',kind:'fix',content:'### Fix recorded\n\nPreserve the previous key.'}));await page.clock.fastForward(5500);await expect(page.locator('.pj-fix')).toContainText('Preserve the previous key');await expect(page.locator('.pj-body details')).toHaveAttribute('open');await expect(page.locator('[data-note]')).toHaveValue('Keep my draft');expect(await page.locator('.pj-scroll').evaluate(e=>e.scrollTop)).toBe(scroll);});
test('project switching isolates entries and preserves drafts',async({page})=>{await start(page);await page.getByText('Add your note or question',{exact:true}).click();await page.locator('[data-note]').fill('Project A draft');await page.evaluate(()=>window.xnautJournal.mount(document.querySelector('#journal'),'OTHER',()=>{}));await expect(page.locator('[data-title]')).toHaveText('Other · Live Journal');await expect(page.locator('[data-opening]')).toHaveText('Other project history');await expect(page.locator('.pj-entry')).toHaveCount(0);await expect(page.locator('[data-note]')).toHaveValue('');await page.evaluate(()=>window.xnautJournal.mount(document.querySelector('#journal'),'DEMO',()=>{}));await expect(page.locator('[data-note]')).toHaveValue('Project A draft');});
test('failed note save retains input and valid save appears with attribution',async({page})=>{await start(page);await page.getByText('Add your note or question',{exact:true}).click();await page.locator('[data-ticket]').fill('OTHER-1');await page.locator('[data-note]').fill('Verify the restore before deletion');await page.evaluate(()=>{window.failSave=true;});await page.getByRole('button',{name:'Save to Journal'}).click();await expect(page.locator('[data-status]')).toContainText('Ticket is outside');await expect(page.locator('[data-note]')).toHaveValue('Verify the restore before deletion');await page.evaluate(()=>{window.failSave=false;});await page.locator('[data-ticket]').fill('DEMO-1');await page.getByRole('button',{name:'Save to Journal'}).click();await expect(page.locator('[data-id="saved"]')).toContainText('Verify the restore before deletion');await expect(page.locator('[data-note]')).toHaveValue('');});
test('workstream filtering and source links keep exact identity',async({page})=>{await start(page);await page.getByLabel('Journal workstream').selectOption('DEMO-2');await expect(page.locator('.pj-entry')).toHaveCount(1);await page.getByRole('button',{name:'Source conversation ↗'}).click();expect(await page.evaluate(()=>window.openedConversation)).toEqual(['reviewer','thread-one']);});
test('untrusted content cannot execute and narrow panes do not overflow',async({page})=>{await start(page);await page.evaluate(()=>{window.journalData.entries.push({...window.journalData.entries[0],id:'unsafe',kind:'finding',content:'<script>window.pwned=true</script>\n<img src=x onerror="window.pwned=true">\n[bad](javascript:alert(1))'});return window.journalInstance.refresh();});expect(await page.evaluate(()=>window.pwned)).toBeUndefined();await expect(page.locator('.pj script,.pj [onerror],.pj a[href^="javascript:"]')).toHaveCount(0);await page.locator('#journal').evaluate(e=>{e.style.width='420px';});expect(await page.locator('.pj-scroll').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBeTruthy();});
test('slow polling does not overlap requests',async({page})=>{await page.clock.install();await start(page);await page.evaluate(()=>{const invoke=window.__TAURI__.core.invoke;window.pendingCount=0;window.__TAURI__.core.invoke=(name,args)=>{if(name==='project_journal_read'){window.pendingCount++;return new Promise(resolve=>{window.finishRead=async()=>resolve(await invoke(name,args));});}return invoke(name,args);};});await page.clock.fastForward(21000);expect(await page.evaluate(()=>window.pendingCount)).toBe(1);await page.evaluate(()=>window.finishRead());});

test('saved context links open the exact Wiki page offline',async({page})=>{await start(page);await page.locator('[data-opening]').getByRole('button',{name:'Previous Journal'}).click();expect(await page.evaluate(()=>window.openedWiki)).toBe('Development/journal/2026-10-02.md');});

test('run details are folded behind a readable review summary',async({page})=>{await start(page);await page.evaluate(()=>{window.journalData.entries.push({...window.journalData.entries[0],id:'receipt',run_id:'run-1',preview:'### Backup review\n\nReview: changes requested. The diff is missing.',content:'### Full record\n\n```json\n{"input_hash":"technical-evidence"}\n```'});return window.journalInstance.refresh();});await expect(page.locator('[data-id="receipt"]')).toContainText('Review: changes requested');await expect(page.locator('[data-id="receipt"] pre')).not.toBeVisible();await page.getByText('Execution details and evidence',{exact:true}).click();await expect(page.locator('[data-id="receipt"] pre')).toContainText('technical-evidence');});
