import {test,expect} from '@playwright/test';
async function start(page){
 await page.route('https://**/*',route=>route.abort());
 await page.addInitScript(()=>{
  const project={key:'DEMO',name:'GC-DevOps',root:'/demo',purpose:'System reconnaissance, upgrade planning and operator handoffs',vault_path:'/vault/work/GC-DevOps'};
  const docs={ 'Development/recon/current-system.md':{content:'# Current system\n\nA verified baseline for the next operator.\n\n## Architecture\n\n| Component | State |\n| --- | --- |\n| Review API | Local prototype |\n| Production changes | Not authorized |\n\n## Evidence\n\nVerified: 1 October 2026\n\n```sh\ngit status --short\n```\n\n## Next steps\n\n- Review outstanding findings\n- Validate the upgrade plan',created_by:'Andre',created_at:'2026-10-01T08:00:00Z',updated_by:'NautBot',updated_at:'2026-10-03T12:00:00Z',revision:2}, 'Development/handoffs/run-1-failed.md':{content:'# Handoff · DEMO-4\n\n## Confirmed outcome\nRecon completed. Upgrade execution has not started.\n\n## Where to continue\nReview the missing runtime evidence.',created_by:'xNAUT recorded checkpoint',created_at:'2026-10-03T12:00:00Z',updated_by:'xNAUT recorded checkpoint',updated_at:'2026-10-03T12:00:00Z',revision:1}};
  let counter=2;const calls=[];
  const read=path=>{const d=docs[path];if(!d)throw Error('Missing document');return {id:path,path,title:d.content.split('\n')[0].replace(/^# /,''),hash:'hash-'+d.revision,...d,history:Array.from({length:d.revision},(_,i)=>({number:i+1,actor:i?'NautBot':'Andre',at:'2026-10-01T08:00:00Z',summary:i?'Added evidence':'Initial recon',content:d.content}))};};
  const run={run_id:'run-2',ticket:'DEMO-7',state:'running',agent_handle:'NautBot',runtime_id:'codex',initiated_by:'Andre',last_signal:'Reviewing package evidence',last_seen_at:1791028800000,started_at:1791028700000};
  window.__wikiTest={docs,calls,run};
  window.__TAURI__={core:{convertFileSrc:p=>'asset://localhost'+p,invoke:async(command,args={})=>{
   calls.push({command,args});
   if(command==='project_wiki_projects')return [project,{...project,key:'OTHER',name:'Other project',root:'/other'}];
   if(command==='project_wiki_overview')return {project:args.project==='OTHER'?{...project,key:'OTHER',name:'Other project'}:project,documents:args.project==='OTHER'?[]:Object.keys(docs).map(path=>({path,title:read(path).title})),runs:args.project==='OTHER'?[]:[run],activity:args.project==='OTHER'?[]:[{id:'a',at:'2026-10-03T12:00:00Z',kind:'run running',actor:'NautBot',ticket:'DEMO-7',run_id:'run-2',detail:'Reviewing package evidence'},{id:'b',at:'2026-10-01T08:00:00Z',kind:'ticket.created',actor:'Andre',ticket:'DEMO-7',detail:'Review before upgrade'}],activity_total:args.project==='OTHER'?0:2,observed_at:'2026-10-03T12:00:00Z',warnings:[]};
   if(command==='project_wiki_read')return read(args.path);
   if(command==='project_wiki_save'){const r=args.request;const old=docs[r.path];if((old?'hash-'+old.revision:null)!==r.expected_hash)throw Error('This page changed since you opened it. Your draft is preserved. Reload the current page before merging your changes.');docs[r.path]={...old,content:r.content,created_by:old?.created_by||'Andre',created_at:old?.created_at||new Date().toISOString(),updated_by:'Andre',updated_at:new Date().toISOString(),revision:old?old.revision+1:1};counter++;return read(r.path);}
   if(command==='project_wiki_source'){if(args.kind==='log'&&window.__wikiTest.missingLog)throw Error('The saved output log is no longer available');return {title:args.kind+' · '+args.id,text:'Saved '+args.kind+' for '+args.id};}
   if(command==='project_wiki_asset')return '/vault/work/GC-DevOps/'+args.path;
   if(command==='plugin:shell|open')return null;
   throw Error('Unexpected command '+command);
  }}};
 });
 await page.goto('/wiki-preview.html');await expect(page.locator('[data-project-name]')).toHaveText('GC-DevOps');await expect(page.locator('.pw-stats')).toBeVisible();
}
test('project overview combines live work, handoffs and saved activity',async({page})=>{await start(page);await expect(page.locator('.pw-run')).toContainText('Andre');await expect(page.locator('.pw-run')).toContainText('NautBot');await expect(page.locator('.pw-doc-link')).toContainText('Handoff');await page.getByRole('button',{name:'Conversation context ↗',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Saved context for run-2');await page.getByRole('button',{name:'Close dialog'}).click();await page.selectOption('#project-select','OTHER');await expect(page.locator('[data-project-name]')).toHaveText('Other project');await expect(page.locator('.pw-main')).not.toContainText('DEMO-7');});
test('manual page saves to the canonical project path and appears in navigation',async({page})=>{await start(page);await page.getByRole('button',{name:'＋ Add page'}).click();await page.locator('[data-path]').fill('Development/wiki/operator-notes.md');await page.locator('[data-content]').fill('# Operator notes\n\nKeep the original backup before upgrading.');await page.getByRole('button',{name:'Save to Vault',exact:true}).click();await expect(page.locator('.pw-article')).toContainText('Keep the original backup');await expect(page.locator('.pw-provenance')).toContainText('Andre');expect(await page.evaluate(()=>window.__wikiTest.docs['Development/wiki/operator-notes.md'].content)).toContain('original backup');});
test('stale editor keeps its draft and refuses to overwrite a Vault change',async({page})=>{await start(page);await page.locator('[data-pages]').getByRole('button',{name:'Current system',exact:true}).click();await page.getByRole('button',{name:'Edit page',exact:true}).click();await page.locator('[data-content]').fill('# My unsaved draft');await page.locator('[data-summary]').fill('My update');await page.evaluate(()=>{const d=window.__wikiTest.docs['Development/recon/current-system.md'];d.content='# New human evidence';d.revision++;});await page.getByRole('button',{name:'Save to Vault',exact:true}).click();await expect(page.locator('[data-notice]')).toContainText('changed since');await expect(page.locator('[data-content]')).toHaveValue('# My unsaved draft');expect(await page.evaluate(()=>window.__wikiTest.docs['Development/recon/current-system.md'].content)).toBe('# New human evidence');});
test('page provenance, history, contents and copy controls are available',async({page})=>{await start(page);await page.locator('[data-pages]').getByRole('button',{name:'Current system',exact:true}).click();await expect(page.locator('.pw-provenance')).toContainText('Andre');await expect(page.locator('.pw-provenance')).toContainText('NautBot');await expect(page.locator('[data-toc]')).toContainText('Architecture');await expect(page.locator('.pw-copy')).toBeVisible();await page.getByRole('button',{name:'History · 2',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Initial recon');await expect(page.getByRole('dialog')).toContainText('Added evidence');});
test('activity filters preserve exact links and unavailable evidence is visible',async({page})=>{await start(page);await page.getByRole('button',{name:'Activity history',exact:true}).click();await page.getByLabel('Filter by person or Agent').selectOption('Andre');await expect(page.locator('.pw-event')).toHaveCount(1);await expect(page.locator('.pw-event')).toContainText('ticket.created');await page.getByLabel('Filter by person or Agent').selectOption('');await page.evaluate(()=>{window.__wikiTest.missingLog=true;});await page.getByRole('button',{name:'Logs ↗',exact:true}).click();await expect(page.locator('[data-notice]')).toContainText('no longer available');});
test('unsafe Markdown cannot execute event handlers or javascript links',async({page})=>{await start(page);await page.evaluate(()=>{window.__wikiTest.docs['Development/recon/current-system.md'].content='# Untrusted\n\n<img src="x" onerror="window.__unsafe=true">\n<script>window.__unsafe=true</script>\n[bad](javascript:alert(1))';});await page.locator('[data-pages]').getByRole('button',{name:'Current system',exact:true}).click();await expect(page.locator('.pw-article')).toContainText('Untrusted');expect(await page.evaluate(()=>window.__unsafe)).toBeUndefined();await expect(page.locator('.pw-article [onerror],.pw-article script,.pw-article a[href^="javascript:"]')).toHaveCount(0);});
test('a draft survives switching projects without leaking into the other project',async({page})=>{await start(page);await page.getByRole('button',{name:'＋ Add page'}).click();await page.locator('[data-content]').fill('# Unsaved project note');await page.selectOption('#project-select','OTHER');await expect(page.locator('[data-main]')).not.toContainText('Unsaved project note');await page.selectOption('#project-select','DEMO');await page.getByRole('button',{name:'＋ Add page'}).click();await expect(page.locator('[data-content]')).toHaveValue('# Unsaved project note');});
test('overview has no horizontal overflow at native preview width',async({page})=>{await page.setViewportSize({width:1200,height:820});await start(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:'/tmp/xnaut-455-overview.png'});});

test('returning to a conflicting draft requires an explicit merge base',async({page})=>{
 await start(page);await page.locator('[data-pages]').getByRole('button',{name:'Current system',exact:true}).click();await page.getByRole('button',{name:'Edit page',exact:true}).click();await page.locator('[data-content]').fill('# My draft');await page.locator('[data-summary]').fill('Merge evidence');await page.evaluate(()=>{const d=window.__wikiTest.docs['Development/recon/current-system.md'];d.content='# New saved evidence';d.revision++;});await page.getByRole('button',{name:'Save to Vault',exact:true}).click();await page.getByRole('button',{name:'Read current version (keep my draft)',exact:true}).click();await page.getByRole('button',{name:'Edit page',exact:true}).click();await expect(page.locator('[data-content]')).toHaveValue('# My draft');await page.getByRole('button',{name:'Compare and merge',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('New saved evidence');await page.getByRole('button',{name:'Use this revision as merge base',exact:true}).click();await page.locator('[data-content]').fill('# Merged evidence');await page.getByRole('button',{name:'Save to Vault',exact:true}).click();await expect(page.locator('.pw-article')).toContainText('Merged evidence');
});
test('local image and video links render with offline Markdown',async({page})=>{
 await start(page);await page.evaluate(()=>{window.__wikiTest.docs['Development/recon/current-system.md'].content='# Media\n\n![Evidence](../wiki/assets/test.png)\n\n<video controls src="../wiki/assets/test.mp4"></video>';});await page.locator('[data-pages]').getByRole('button',{name:'Current system',exact:true}).click();await expect(page.locator('.pw-article img')).toHaveAttribute('src',/asset:.*test.png/);await expect(page.locator('.pw-article video')).toHaveAttribute('src',/asset:.*test.mp4/);await expect(page.locator('.pw-article video')).toHaveAttribute('controls','');
});
test('live overview refreshes the displayed run evidence',async({page})=>{
 await page.clock.install();await start(page);await page.evaluate(()=>{window.__wikiTest.run.last_signal='New persisted progress';});await page.clock.fastForward(16000);await expect(page.locator('.pw-run')).toContainText('New persisted progress');
});
test('a slow history refresh completes without overlapping polls',async({page})=>{
 await page.clock.install();await start(page);await page.evaluate(()=>{const invoke=window.__TAURI__.core.invoke;window.__slowCount=0;window.__TAURI__.core.invoke=async(cmd,args)=>{const value=await invoke(cmd,args);if(cmd==='project_wiki_overview'){window.__slowCount++;return new Promise(resolve=>{window.__finishRefresh=()=>resolve({...value,project:{...value.project,purpose:'Slow refresh completed'}});});}return value;};});await page.getByRole('button',{name:'↻ Refresh',exact:true}).click();await page.clock.fastForward(31000);expect(await page.evaluate(()=>window.__slowCount)).toBe(1);await page.evaluate(()=>window.__finishRefresh());await expect(page.locator('[data-project-purpose]')).toHaveText('Slow refresh completed');
});
test('history dialog inherits the Wiki theme and narrow panes remain usable',async({page})=>{
 await start(page);await page.locator('[data-pages]').getByRole('button',{name:'Current system',exact:true}).click();await page.getByRole('button',{name:'History · 2',exact:true}).click();expect(await page.locator('.pw-dialog').evaluate(e=>getComputedStyle(e).backgroundColor)).not.toBe('rgba(0, 0, 0, 0)');await page.getByRole('button',{name:'Close dialog'}).click();await page.locator('#wiki-preview').evaluate(e=>{e.style.width='480px';});expect(await page.locator('.pw-layout').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBeTruthy();await expect(page.getByRole('button',{name:'Edit page',exact:true})).toBeVisible();
});

test('Journal reads as a document in Wiki without internal capture metadata',async({page})=>{await start(page);await page.evaluate(()=>{window.__wikiTest.docs['Development/recon/current-system.md'].content='# Live Journal\n\n<!-- xnaut-journal-entry {"id":"internal-capture-id","actor":"Andre"} -->\n### Decision\n\nPreserve existing backups.';});await page.locator('[data-pages]').getByRole('button',{name:'Current system',exact:true}).click();await expect(page.locator('.pw-article')).toContainText('Preserve existing backups');await expect(page.locator('.pw-article')).not.toContainText('internal-capture-id');});
