// XNAUT-455. One project view over canonical Vault files and durable run receipts.
// Imported references and the existing conversation notebooks remain in Wiki tabs.
(function () {
  'use strict';
  const invoke = (command, args = {}) => window.__TAURI__.core.invoke(command, args);
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date = value => { if (!value) return 'Not recorded'; const d = new Date(value); return isNaN(d) ? String(value) : d.toLocaleString(undefined, {dateStyle:'medium',timeStyle:'short'}) + ' · ' + Intl.DateTimeFormat().resolvedOptions().timeZone; };
  const terminal = state => ['done','failed','retired'].includes(state);
  const strip = content => String(content).replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '');
  const drafts = new Map();
  const instances = new WeakMap();
  const group = path => /Development\/journal\//.test(path) ? 'Journals' : /^Memory\//.test(path) ? 'Saved project memory' : /handoffs\//.test(path) ? 'Handoffs' : /(?:^|[\/_-])(?:recon|review|audit)(?:[\/_.-]|$)/i.test(path) ? 'Recon & reviews' : /(?:plans|features|decisions)/i.test(path) ? 'Plans & decisions' : /(?:docu|references)/i.test(path) ? 'Reference documents' : 'Project documents';
  function mount(host, root) {
    if (!host) return;
    instances.get(host)?.dispose();
    let data = null, selected = '', doc = null, editing = false, stopped = false, generation = 0, tab = 'overview', timer;
    let editHash = null, refreshing = false;
    let filter = '', activityFilter = '', actorFilter = '', outcomeFilter = '', fromFilter = '';
    host.innerHTML = `<div class="pw"><header class="pw-header"><div><div class="pw-eyebrow">PROJECT KNOWLEDGE</div><h1 data-project-name>Project Wiki</h1><p data-project-purpose>Opening the project Vault…</p></div><div class="pw-head-actions"><span class="pw-vault">Vault connected</span><button data-refresh title="Refresh documents and activity">↻ Refresh</button><button class="pw-primary" data-add>＋ Add page</button></div></header><div class="pw-notice" role="status" data-notice hidden></div><div class="pw-layout"><nav class="pw-nav" aria-label="Project Wiki"><input type="search" data-search placeholder="Find a page…" aria-label="Find a Wiki page"><button data-home>Overview</button><button data-activity>Activity history</button><div data-pages></div><div class="pw-nav-footer">Shared with your Vault<br><span data-observed></span></div></nav><main class="pw-main" data-main></main></div></div>`;
    const $ = s => host.querySelector(s);
    function notice(message, error = false) { const n = $('[data-notice]'); n.hidden = !message; n.textContent = message; n.classList.toggle('error', error); }
    function remember() { if (!editing) return; const el = $('[data-content]'); if (el) drafts.set(root + ':' + selected, {content:el.value,path:$('[data-path]')?.value || selected,summary:$('[data-summary]')?.value || '',hash:editHash}); }
    function leave() { remember(); editing = false; }
    function drawNav() {
      const list = $('[data-pages]'); list.replaceChildren();
      const groups = new Map();
      for (const page of data.documents) { if (filter && !(page.title + ' ' + page.path).toLowerCase().includes(filter.toLowerCase())) continue; const name = group(page.path); if (!groups.has(name)) groups.set(name, []); groups.get(name).push(page); }
      for (const [name, pages] of groups) { const section = document.createElement('div'); section.className = 'pw-nav-section'; section.innerHTML = `<h3>${esc(name)} <span>${pages.length}</span></h3>`; for (const page of pages.slice(0,60)) { const b = document.createElement('button'); b.className = page.path === selected ? 'active' : ''; b.textContent = page.title; b.title = page.path; b.onclick = () => openPage(page.path); section.append(b); } if(pages.length>60){const more=document.createElement("p");more.className="pw-muted";more.textContent="Showing 60 of "+pages.length+". Search to narrow the list.";section.append(more);} list.append(section); }
      if (!data.documents.length) list.innerHTML = '<p class="pw-muted">Add your first project page, or open an existing document from the Vault.</p>';
      if (data.documents.length && !groups.size) list.innerHTML = '<p class="pw-muted">No matching pages.</p>';
      $('[data-home]').classList.toggle('active', tab === 'overview'); $('[data-activity]').classList.toggle('active', tab === 'activity');
    }
    function sourceButtons(run) { return `<div class="pw-source-links"><button data-source="run" data-id="${esc(run.run_id)}">Run record ↗</button><button data-source="context" data-id="${esc(run.run_id)}">Conversation context ↗</button><button data-source="log" data-id="${esc(run.run_id)}">Logs ↗</button>${run.ticket ? `<button data-source="ticket" data-id="${esc(run.ticket)}">${esc(run.ticket)} ↗</button>` : ''}</div>`; }
    function bindSources() { host.querySelectorAll('[data-event-page]').forEach(b=>{b.onclick=()=>openPage(b.dataset.eventPage);}); host.querySelectorAll('[data-source]').forEach(b => { b.onclick = () => source(b.dataset.source, b.dataset.id); }); }
    async function source(kind, id) { try { const value = await invoke('project_wiki_source', {project:data.project.key,kind,id}); if (!stopped) { const modal=dialog(value.title, `<p class="pw-muted">${value.truncated ? 'Showing the most recent 128 KB. ' : ''}Saved source record</p><pre class="pw-source">${esc(value.text)}</pre>`); if(value.thread_id && window.xnautOpenAgentSpace){const b=document.createElement('button');b.textContent='Open original conversation ↗';b.onclick=()=>{modal.remove();window.xnautOpenAgentSpace(value.agent,value.thread_id);};modal.querySelector('.pw-dialog-body').prepend(b);} } } catch (error) { notice(String(error), true); } }
    function dialog(title, html) { const backdrop = document.createElement('div'); backdrop.className = 'pw-dialog-backdrop'; backdrop.innerHTML = `<section class="pw-dialog" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header><h2>${esc(title)}</h2><button aria-label="Close dialog">✕</button></header><div class="pw-dialog-body">${html}</div></section>`; $('.pw').append(backdrop); const close = () => {backdrop.remove();}; backdrop.querySelector('header button').onclick = close; backdrop.onclick = e => {if (e.target === backdrop) close();}; backdrop.onkeydown = e => {if (e.key === 'Escape') close();}; backdrop.querySelector('button').focus(); return backdrop; }
    function overview() {
      tab = 'overview'; selected = ''; drawNav();
      const active = data.runs.filter(r => !terminal(r.state)); const handoffs = data.documents.filter(d => d.path.includes('/handoffs/')).slice().sort((a,b)=>b.path.localeCompare(a.path));
      $('[data-main]').innerHTML = `<div class="pw-kicker">WHERE THINGS STAND</div><h2 class="pw-page-title">The project, in one place.</h2><p class="pw-intro">Read what we know. See what is happening. Pick up where the last person left off.</p><div class="pw-stats"><div><strong>${data.documents.length}</strong><span>Vault pages</span></div><div><strong>${active.length}</strong><span>Active or waiting runs</span></div><div><strong>${handoffs.length}</strong><span>Saved handoffs</span></div><div><strong>${data.activity_total}</strong><span>Recorded activities</span></div></div><section class="pw-section"><div class="pw-section-heading"><h3>Current work</h3><span>Observed ${esc(date(data.observed_at))}</span></div>${active.length ? active.map(r => `<article class="pw-run"><div><span class="pw-status ${esc(r.state)}">${esc(r.state)}</span><strong>${esc(r.ticket || r.run_id)}</strong><span class="pw-muted">${esc(r.agent_handle)} · ${esc(r.runtime_id)}</span></div><p>${esc(r.last_signal || r.waiting_on || 'No current progress note recorded.')}</p><small>Last signal ${esc(date(r.last_seen_at))} · Initiator ${esc(r.initiated_by || 'not recorded')}</small>${sourceButtons(r)}</article>`).join('') : '<div class="pw-empty">No active runs are recorded for this project. Previous work remains in the activity history and handoffs.</div>'}</section><div class="pw-two"><section class="pw-section"><h3>Continue from a handoff</h3>${handoffs.length ? handoffs.slice(0,5).map(p => `<button class="pw-doc-link" data-page="${esc(p.path)}"><span>↳</span><div><strong>${esc(p.title)}</strong><small>${esc(p.path)}</small></div><span>→</span></button>`).join('') : '<p class="pw-muted">When a recorded run stops, its checkpoint will appear here with outcomes, evidence and next steps.</p>'}</section><section class="pw-section"><h3>Recent activity</h3>${data.activity.slice(0,5).map(a => `<div class="pw-mini-event"><span class="pw-dot"></span><div><strong>${esc(a.kind)}</strong><p>${esc(a.actor || 'Actor not recorded')} · ${esc(a.ticket || a.path?.split('/').pop() || '')}</p><small>${esc(date(a.at))}</small></div></div>`).join('') || '<p class="pw-muted">No saved activity for this project yet.</p>'}<button data-all-activity>View activity history →</button></section></div>`;
      $('[data-all-activity]').onclick = activity; host.querySelectorAll('[data-page]').forEach(b => {b.onclick = () => openPage(b.dataset.page);}); bindSources();
    }
    function activity() {
      tab = 'activity'; selected = ''; drawNav();
      const actors = [...new Set(data.activity.map(a => a.actor || 'Not recorded'))].sort();
      $('[data-main]').innerHTML = `<div class="pw-kicker">PROJECT RECORD</div><h2 class="pw-page-title">Activity history</h2><p class="pw-intro">Saved events and run receipts, with links back to their evidence.</p><div class="pw-filters"><input data-activity-search aria-label="Search activity" placeholder="Search ticket, action or outcome…" value="${esc(activityFilter)}"><select data-actor aria-label="Filter by person or Agent"><option value="">All people & Agents</option>${actors.map(a => `<option ${a === actorFilter ? 'selected' : ''}>${esc(a)}</option>`).join('')}</select><select data-outcome aria-label="Filter by outcome"><option value="">All outcomes</option>${['running','done','failed','blocked','retired','ticket.updated','ticket.created'].map(a => `<option ${a === outcomeFilter ? 'selected' : ''}>${a}</option>`).join('')}</select><input type="date" data-from aria-label="Activity since date" value="${esc(fromFilter)}"></div><div data-events></div>`;
      const render = () => {const events = data.activity.filter(a => (!actorFilter || a.actor === actorFilter) && (!outcomeFilter || a.kind.includes(outcomeFilter)) && (!fromFilter || String(a.at) >= fromFilter) && JSON.stringify(a).toLowerCase().includes(activityFilter.toLowerCase())); $('[data-events]').innerHTML = `<p class="pw-muted">${events.length} shown · ${data.activity_total} recorded${data.activity_total > data.activity.length ? ' · latest 1,000 loaded' : ''}</p>` + events.map(a => `<article class="pw-event"><div class="pw-event-date">${esc(date(a.at))}</div><div><h3>${esc(a.kind)} <span>${esc(a.ticket || '')}</span></h3><p class="pw-muted">${esc(a.actor || 'Actor not recorded')}</p><p class="pw-event-detail">${esc(a.detail)}</p><div class="pw-source-links">${a.path ? `<button data-event-page="${esc(a.path)}">Page ↗</button>` : ''}${a.ticket ? `<button data-source="ticket" data-id="${esc(a.ticket)}">Ticket ↗</button>` : ''}${a.run_id ? sourceButtons({run_id:a.run_id}) : ''}</div></div></article>`).join(''); bindSources();};
      $('[data-activity-search]').oninput = e => {activityFilter=e.target.value;render();}; $('[data-actor]').onchange = e => {actorFilter=e.target.value;render();}; $('[data-outcome]').onchange = e => {outcomeFilter=e.target.value;render();}; $('[data-from]').onchange = e => {fromFilter=e.target.value;render();}; render();
    }
    async function openPage(path) {
      leave(); selected = path; tab = 'page'; const seq = ++generation; notice('Opening page…');
      try { const next = await invoke('project_wiki_read', {project:data.project.key,path}); if (stopped || seq !== generation) return; doc = next; notice(''); drawNav(); renderPage(); } catch (e) { if (seq === generation) notice(String(e), true); }
    }
    function renderPage() {
      $('[data-main]').innerHTML = `<div class="pw-document-head"><div><div class="pw-kicker">${esc(group(doc.path))}</div><h2 class="pw-page-title">${esc(doc.title)}</h2><p class="pw-path">${esc(doc.path)}</p></div><div class="pw-head-actions"><button data-revisions>History · ${doc.revision}</button><button class="pw-primary" data-edit>Edit page</button></div></div><div class="pw-provenance"><span>Created by <strong>${esc(doc.created_by)}</strong><small>${esc(date(doc.created_at))}</small></span><span>Latest revision by <strong>${esc(doc.updated_by)}</strong><small>${esc(date(doc.updated_at))}</small></span></div><div class="pw-reading"><article class="pw-article xnaut-md" data-article></article><aside class="pw-toc"><span>ON THIS PAGE</span><nav data-toc></nav></aside></div>`;
      const run=data.runs.find(r=>doc.path.includes('/handoffs/'+r.run_id+'-'));if(run){const links=document.createElement('div');links.innerHTML=sourceButtons(run);$('[data-main]').querySelector('.pw-provenance').after(links);bindSources();}
      $('[data-edit]').onclick = edit; $('[data-revisions]').onclick = revisions;
      renderMarkdown($('[data-article]'), strip(doc.content), doc.path);
    }
    async function renderMarkdown(el, markdown, path) {
      // Parse off-DOM, then allowlist before insertion. Stored/raw HTML is data.
      let html; try { const marked = await window.xnautMarkdown.loadMarked(); html = marked.parse(markdown); } catch (_) {
        const media=[];
        const prepared=markdown.replace(/!\[([^\]]*)\]\(([^)]+)\)|<video\s+[^>]*src=["']([^"']+)["'][^>]*>\s*<\/video>/gi,(_,alt,src,video)=>{const token='XNAUTMEDIA'+media.length+'END';media.push(video?`<video controls src="${esc(video)}"></video>`:`<img alt="${esc(alt)}" src="${esc(src)}">`);return token;});
        html=window.xnautMarkdown.render(prepared).replace(/XNAUTMEDIA(\d+)END/g,(_,i)=>media[Number(i)]);
      }
      const parsed = new DOMParser().parseFromString(html, 'text/html');
      const allowed = new Set('P H1 H2 H3 H4 H5 H6 UL OL LI STRONG EM DEL CODE PRE BLOCKQUOTE HR BR TABLE THEAD TBODY TR TH TD A IMG VIDEO SOURCE DETAILS SUMMARY INPUT'.split(' '));
      parsed.body.querySelectorAll('*').forEach(n => { if (!allowed.has(n.tagName)) { n.replaceWith(document.createTextNode(n.textContent)); return; } for (const a of [...n.attributes]) {if (!['href','src','alt','title','class','type','checked','disabled','controls','open'].includes(a.name)) n.removeAttribute(a.name);} if (n.tagName === 'INPUT') {n.type='checkbox';n.disabled=true;} });
      for (const n of parsed.body.querySelectorAll('[href],[src]')) { const attr = n.hasAttribute('href') ? 'href' : 'src'; const value = n.getAttribute(attr) || ''; if (/^(https?:|#)/i.test(value)) continue; n.removeAttribute(attr); if (!/^[a-z]+:/i.test(value) && !value.startsWith('/')) {try {const parts = path.split('/');parts.pop();for (const v of value.split('/')) {if (v === '..') parts.pop();else if (v && v !== '.') parts.push(v);} const rel = parts.join('/'); if (attr === 'href' && rel.endsWith('.md')) {n.dataset.pageLink = rel;} else { const asset = await invoke('project_wiki_asset', {project:data.project.key,path:rel});n.setAttribute(attr,window.__TAURI__.core.convertFileSrc(asset)); }} catch (_) { n.setAttribute('title','Attachment unavailable');}} }
      if (!el.isConnected) return; el.replaceChildren(...parsed.body.childNodes);
      el.querySelectorAll('a').forEach(a => {a.onclick = e => {e.preventDefault();if (a.dataset.pageLink) return openPage(a.dataset.pageLink);const url=a.getAttribute('href');if (url?.startsWith('#')) {document.getElementById(url.slice(1))?.scrollIntoView();return;}if (/^https?:/i.test(url || '')) invoke('plugin:shell|open',{path:url}).catch(e=>notice(String(e),true));};});
      el.querySelectorAll('pre').forEach(pre => {const b=document.createElement('button');b.textContent='Copy';b.className='pw-copy';b.onclick=async()=>{try {await navigator.clipboard.writeText(pre.querySelector('code')?.textContent || pre.textContent);b.textContent='Copied';}catch(e){notice(String(e),true);}};pre.append(b);});
      el.querySelectorAll('img').forEach(img => {img.tabIndex=0;img.onclick=()=>dialog(img.alt || 'Image',`<img class="pw-lightbox" src="${esc(img.src)}" alt="${esc(img.alt)}">`);img.onkeydown=e=>{if(e.key==='Enter')img.click();};});el.querySelectorAll('video').forEach(v=>{v.controls=true;});
      const toc=$('[data-toc]');if(toc){toc.replaceChildren();el.querySelectorAll('h1,h2,h3').forEach((h,i)=>{h.id='pw-heading-'+i;const b=document.createElement('button');b.textContent=h.textContent;b.onclick=()=>h.scrollIntoView({behavior:'smooth',block:'start'});toc.append(b);});}
    }
    function revisions() {const d=dialog('Revision history',doc.history.slice().reverse().map(r=>`<details class="pw-revision"><summary><strong>Revision ${r.number} · ${esc(r.actor)}</strong><small>${esc(date(r.at))}</small><p>${esc(r.summary)}</p></summary><pre>${esc(r.content)}</pre></details>`).join(''));return d;}
    function edit() {
      editing=true; const saved=drafts.get(root+':'+selected); editHash=saved ? saved.hash : (doc?.hash ?? null); const content=saved?.content ?? doc?.content ?? '# New page\n\n';
      $('[data-main]').innerHTML = `<div class="pw-kicker">${doc ? 'EDIT VAULT DOCUMENT' : 'NEW VAULT DOCUMENT'}</div><h2 class="pw-page-title">${doc ? esc(doc.title) : 'Add a project page'}</h2><p class="pw-intro">Saved in the Vault, visible here. Each save keeps its author and revision.</p><label class="pw-label">Document path<input data-path value="${esc(saved?.path || selected || 'Development/wiki/new-page.md')}" ${doc ? 'readonly' : ''}></label><label class="pw-label">Content · Markdown<textarea data-content spellcheck="true">${esc(content)}</textarea></label><div class="pw-editor-tools"><button data-attach>Attach image or video</button><span class="pw-muted">Markdown supports headings, tables, links and code blocks.</span><input data-file type="file" accept="image/png,image/jpeg,image/webp,image/gif,video/mp4,video/webm" hidden></div><label class="pw-label">What changed?<input data-summary placeholder="Describe this revision" value="${esc(saved?.summary || (doc ? '' : 'Create project page'))}"></label><div class="pw-editor-actions"><button data-cancel>Back to page</button><button class="pw-primary" data-save>Save to Vault</button></div>`;
      if(saved && doc && saved.hash !== doc.hash){
        notice('Your draft is based on an older revision. Compare it with the current page before saving.',true);
        const merge=document.createElement('button');merge.textContent='Compare and merge';merge.onclick=()=>{const d=dialog('Merge with current Vault page',`<p>Current saved version is below. Edit your draft to retain the changes you need, then accept this version as your merge base.</p><pre>${esc(doc.content)}</pre><button data-accept-base>Use this revision as merge base</button>`);d.querySelector('[data-accept-base]').onclick=()=>{editHash=doc.hash;remember();d.remove();notice('Current revision selected as merge base. Review your draft before saving.');};};$('[data-notice]').append(' ',merge);
      }
      $('[data-content]').oninput=remember;$('[data-path]').oninput=remember;$('[data-summary]').oninput=remember;
      $('[data-cancel]').onclick=()=>{remember();editing=false;if(doc)renderPage();else overview();notice('Draft kept in this window. Reopen Edit to continue.');};
      $('[data-attach]').onclick=()=>$('[data-file]').click();$('[data-file]').onchange=attach;
      $('[data-save]').onclick=async()=>{remember();const draft=drafts.get(root+':'+selected);const button=$('[data-save]');button.disabled=true;notice('Saving…');try{const savedDoc=await invoke('project_wiki_save',{request:{project:data.project.key,path:draft.path,content:draft.content,expected_hash:draft.hash,summary:draft.summary}});drafts.delete(root+':'+selected);doc=savedDoc;selected=doc.path;editing=false;await refresh(false);renderPage();notice('Saved to Vault. Revision '+doc.revision+' recorded.');}catch(e){notice(String(e),true);if(String(e).includes('changed since')){const reload=document.createElement('button');reload.textContent='Read current version (keep my draft)';reload.onclick=()=>openPage(draft.path);$('[data-notice]').append(' ',reload);}}finally{if(button.isConnected)button.disabled=false;}};
    }
    async function attach(){const file=$('[data-file]').files[0];if(!file)return;if(file.size>10*1024*1024){notice('Attachments must be smaller than 10 MB.',true);return;}try{notice('Saving attachment…');const saved=await invoke('project_wiki_attach',{project:data.project.key,name:file.name,bytes:Array.from(new Uint8Array(await file.arrayBuffer()))});const path=$('[data-path]').value;const parent=path.split('/');parent.pop();const target=saved.path.split('/');while(parent.length&&target.length&&parent[0]===target[0]){parent.shift();target.shift();}const rel='../'.repeat(parent.length)+target.join('/');const text=file.type.startsWith('video/')?`\n<video controls src="${rel}"></video>\n`:`\n![${file.name}](${rel})\n`;const ta=$('[data-content]');ta.setRangeText(text,ta.selectionStart,ta.selectionEnd,'end');remember();notice('Attachment saved; save the page to retain its link.');}catch(e){notice(String(e),true);}}
    async function refresh(redraw=true) { if(refreshing)return; refreshing=true; const seq=++generation;try {const next=await invoke('project_wiki_overview',{project:root});if(stopped||seq!==generation)return;data=next;$('[data-project-name]').textContent=next.project.name;$('[data-project-purpose]').textContent=next.project.purpose || 'Documents, decisions and the work behind them';$('[data-observed]').textContent='Updated '+date(next.observed_at);if(next.warnings.length)notice(next.warnings.join(' · '),true);drawNav();if(redraw&&!editing){if(tab==='overview')overview();else if(tab==='activity')activity();}}catch(e){if(!stopped)notice(String(e),true);}finally{refreshing=false;} }
    $('[data-home]').onclick=()=>{leave();if(data)overview();};$('[data-activity]').onclick=()=>{leave();if(data)activity();};$('[data-search]').oninput=e=>{filter=e.target.value;if(data)drawNav();};$('[data-refresh]').onclick=()=>{if(editing){notice('Your draft is open. Save or leave editing before refreshing.');return;}if(tab==='page'&&selected)openPage(selected);else refresh();};$('[data-add]').onclick=()=>{if(!data)return;leave();selected='';doc=null;tab='page';drawNav();edit();};
    const ready=refresh();timer=setInterval(()=>{if(!host.isConnected){clearInterval(timer);return;}if(!editing&&!document.hidden&&(tab==='overview'||tab==='activity'))refresh(true);},15000);
    const instance={dispose(){remember();stopped=true;clearInterval(timer);},refresh,openPage,ready};instances.set(host,instance);return instance;
  }
  window.xnautProjectWiki={mount,open:async(host,path)=>{const instance=instances.get(host);if(instance){await instance.ready;await instance.openPage(path);}}};
})();
